apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  kustomize.toolkit.fluxcd.io/prune: Disabled
  kustomize.toolkit.fluxcd.io/ssa: Override
resources:
- gatewayclasses.yaml
- gateways.yaml
- httproutes.yaml
- grpcroutes.yaml
- referencegrants.yaml
- backendtlspolicies.yaml
- tlsroutes.yaml
