apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:HG6D26lWmadNFR2apTF0yA/c8sxErl2QZYKglZRubDIJnRFYZ+hD4g==,iv:rlNy6/F6475HFhmtQfAcrywd4qdF1KJNRKgyudqGe30=,tag:xBfdSmxJv6IYco2znGaS2Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:867344433810:key/835f8130-e33d-4cf8-af3c-4fb5a0bb9d4a
          created_at: "2026-01-30T13:29:10Z"
          enc: AQICAHh02qo9Ejv0FmnyeqXt197Sx1HR6uYOTtU++egjUu007wHMLjXf9sMiABclIJjVD11iAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMI3Ty2GyxUswoXpMQAgEQgDtt5WiNLIAjCUoxbOY6oppFoFTAA8tIByBIvxYCr64lxBrv/qo5hESX/ba03zI5VNIduxWI8WgsuWwUag==
          aws_profile: ""
    lastmodified: "2026-01-30T13:29:11Z"
    mac: ENC[AES256_GCM,data:B2dqR3p0rVyhx5zO3G1S/Szcqmf2u0eIAGzsgCKySPSIlsVaFXOswFkk43HjyGDf2hYCPd5z00KwDpeC/43Q2vktcsRaG93rSFf8xqq2ay12bakMvRfYiKKJgKt5erDv44lOHZZ1xBHm++WEkKt17sjLrlOgUQgv64IAqkGfBuI=,iv:4NjU3tDgM2sjIGm8EgEgj/iIJLCMGqTMXZ1nzRPZHik=,tag:5yo8gFFZ22f8Vtj9UYxbmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
