apiVersion: v1
data:
    sops.aws-kms: ENC[AES256_GCM,data:3OHu14TyAXwo4i0MVw1Zywg9RP4Jol4byC1xDQulcg85EjrnDYZ3S3loidGYCB7EL8Fxy4n6ktoFfvBn12gjln+BIA9ARL0FWIzwNqMUOmbkdDIFy23PYm+rssqqwKzjKxP083dM9jS2hFSUnXt1viHJadFprlj1duMbr7C7BGGbw1xQYSdsCPkmM/sohFmtwzkRKKHk9TI=,iv:eSsj/emQU1wXZ/gkfWkHPpYfn7Gp8ab7veXBnUoxYe0=,tag:N4SzojqZEIkm+sTxE4ojyQ==,type:str]
kind: Secret
metadata:
    name: sops-aws-kms
    namespace: flux-system
sops:
    encrypted_regex: ^(data|stringData)$
    kms:
        - arn: arn:aws:kms:ap-south-1:867344433810:key/835f8130-e33d-4cf8-af3c-4fb5a0bb9d4a
          aws_profile: ""
          created_at: "2026-07-06T13:23:31Z"
          enc: AQICAHh02qo9Ejv0FmnyeqXt197Sx1HR6uYOTtU++egjUu007wEJHWHx5tSNBzdnUFE+hVVeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM2E+/X57g7241G1UpAgEQgDvVenjsQB0NM76LJ2b4W2YumYMud+m8l+RxrFI3HqCPPwavtZ2uRhJhviiSydKUUzOZYDqCobNYE7+Msw==
          role: arn:aws:iam::867344433810:role/SopsKmsUser
    lastmodified: "2026-07-06T13:23:32Z"
    mac: ENC[AES256_GCM,data:3aRanZrgZYFi+T8zGUh5ZxO8UZtg7RiJ4BUd0iDy2rssHjdw/fW28Ks87XeGi0TVuWg0sfhs+LQ+1w4qtW6bZV09kNSmtjatAT6vA50EhcMnF7yiWmCuhGkKhb6/6LPUd/5vPiYgUCGQb4/Sy2gsFf0i5hmE+hHIIuR9/FLtNNo=,iv:CQVV866wMUTqVjBce4XOOWyABFs4R4fjkccUlgPCCjA=,tag:VbM57Tg/Fgenowz6kBXu+A==,type:str]
    version: 3.13.2
