apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- seaweedfs-s3-credentials.secret.yaml
- seaweedfs-s3-iam.secret.yaml
- referencegrant.yaml
- helmrelease.yaml
