apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-credentials
    namespace: storage
type: Opaque
stringData:
    seaweedfs_s3_config: ENC[AES256_GCM,data:byDha7DzoKCdi3lqDAW85kRF0WE4o38ROZ8rKNBmGleItScFmOD9kpNzsVfyQShn4Yn5ZPCWU1o2vheBXl7Ln7Oq50fsHUDMcvanZKB7EjQKH9r8qefd2rnY7VfSB/sjXTAwsB7Ou6s7FFoyPZ1jWxMBMcfhdoOgfZPoGjXYZYjBi7LEkrA7Spw6boupgm8b9DzCbSAiPczLuyJML6B2sjIuZW8XzRiOss9uLw1aOP4DiYLpkO7EiEgVqNjJKjVXSeyEL+8F+NeLvCH9qTXtuMfszgPKVYJXcSyN6TpU/kt2kQ+pXOxsHuX+BCTPQC2tVwB3nR9V76A9ehd/y7Slg3QCd0xj7fNTHc1oIr9lxp+d8TzeYnYxSqw6OGCC8GW2fCtM3pU9O3R2VCZbP9Es7nJ1Bgv+Ps1cw1gD3qw7SLf1FS48k8s3BwS/CIfjVJNdlDfxEHzJtA8=,iv:rsGFdlOmMICh0WIvZU5k8FJR7hGYymlvkVoTGa5DEC0=,tag:b/dvi82jSp12LcSX8af3Zw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:ap-south-1:867344433810:key/835f8130-e33d-4cf8-af3c-4fb5a0bb9d4a
          created_at: "2026-07-07T11:53:22Z"
          enc: AQICAHh02qo9Ejv0FmnyeqXt197Sx1HR6uYOTtU++egjUu007wHqdnLtKXlCYe81MsUfR6pkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMxVHG5y6jb7NUWx7MAgEQgDuMDrQ+OUvIl/DRV6fh8qJ7tcJahqKaSVZeCWNUlPn1kktL8vJqUY/M9t4kp6RVq7GY52Qkg/uyIANMNg==
          aws_profile: ""
    lastmodified: "2026-07-09T15:40:14Z"
    mac: ENC[AES256_GCM,data:mCBjZXLcBn1upF49L4EnVYTwnHwRJGREpDxg8c7TgURkeK/hYzjwTZUUlwpKzBRsppZJFqpdEQGk70phGFmMLgDz1/ArStDFRQkvoviKeD1wh3m3jEjQW0oVsx1hA82ES9SF+z3o+XCTV8mbVWRh5vdDiJlemuDGtPCNStp1VJg=,iv:CRWQ2XU6UhLc0Cd2EELckqqasIW+jam2PSx/x6y95L4=,tag:enX184x+2OVD1ENQaTeaUg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.13.2
