apiVersion: v1
kind: Secret
metadata:
    name: renovate-forgejo-token
    namespace: renovate
type: Opaque
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:vey50Hfa6r2HUvbLJJsOTBYlsw7jXbXTrxfQ9wuZfh6JGP9dYqc4hQ==,iv:+hw8FGp3l+6luNMZY1MD5IynoFyYWyxx0aG3lRoANNA=,tag:yj6gf7OXxaSRcxrngvHorA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    kms:
        - arn: arn:aws:kms:ap-south-1:867344433810:key/835f8130-e33d-4cf8-af3c-4fb5a0bb9d4a
          aws_profile: ""
          created_at: "2026-07-15T10:44:42Z"
          enc: AQICAHh02qo9Ejv0FmnyeqXt197Sx1HR6uYOTtU++egjUu007wH5+X895jo450XBYrNWnWBrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMztFaLOQ26nMtqIODAgEQgDtldzAUwjI8mYnpNoQ9dMDNp49oyzL9PB3bEMmM+4IPx5JNjtlgfDY4+peFSCpSZvpyrDPiW7qXmDJpQQ==
    lastmodified: "2026-07-15T10:44:43Z"
    mac: ENC[AES256_GCM,data:gDtgJzwBtkz4AlKwBh+rSe/JOwE483ReMIY6L4iisQ2Ag81Vz59bM+9HtU01/w+lCaCZbZmFaCCBzuuNxI9YwYjEYttgDB5l20HNSfDEbKkVO26smONGPYZPee3+QPLPJPRkolmYRQihfAbg5g7Y2+gTykZin0AefjOe6f8yxQw=,iv:aC8oWj25CSTONowwmakPSLKpVrSMx0s2MWusT87LyLk=,tag:cLGakadcsqt6+UEX0Upoyg==,type:str]
    version: 3.13.2
