apiVersion: v1
kind: Secret
metadata:
    name: bw-prod-auth-token
    namespace: networking
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:3CJOy8tZst5wKfYX3XxJ1uh+HeiqpK+HxOqtcrUz0/ojYyUrU2s8wXUTvh5ZBZ1Zn/qpeDuHDto1BQDzrnaKSToKLOSZ3qY+XGWk4LBrN2UL97sX/6ZTPMUAnoucpQ==,iv:EzcvVEI75EE7S8Y5WJMUDAa9awswNfV3uf4qIbVJOt4=,tag:O+FWErRL8K8Eln6CFBqeJA==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    kms:
        - arn: arn:aws:kms:ap-south-1:867344433810:key/835f8130-e33d-4cf8-af3c-4fb5a0bb9d4a
          aws_profile: ""
          created_at: "2026-07-14T13:35:58Z"
          enc: AQICAHh02qo9Ejv0FmnyeqXt197Sx1HR6uYOTtU++egjUu007wE/Zd62lxSiUwItu6xH6yMtAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBhKh+qGbtWiBmCnAAgEQgDsGUr7oaX33b8XZr3SkaWMXxYEJKDE1oqdhjvbUKFYG3OI9zj1vEDGfr4nYOonjxB6vP93hvLIxPnRQgw==
    lastmodified: "2026-07-14T13:35:59Z"
    mac: ENC[AES256_GCM,data:ahHPAUYn+OkPAfzB/Nb7vUg1yV5MDSiSUPPEOBLC3QmWXe5eZ/7Uq9mrnCdhCNIdMo7VaqXrJIkK69EHSuiRB+wbntzBhyQMcS0RsxG4giV1tjKjedp5ectuv24i82CkQ0Jo16aDCyOoH0iIUnv12V4ypm97Ym162L0D0AYUOPI=,iv:fUv9g5GDFsLVb93ox4+BGRfdrr6DcFyiXhflb0/ZT3I=,tag:vpuGsK4Ry7LMuY9lzCAc5A==,type:str]
    version: 3.13.2
