apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argocd.yaml
- grafana.yaml
- hubble.yaml
- metrics.yaml
- otroid-https-redirect.yaml
- pomerium-auth.yaml
- s3.yaml
- seaweedfs.yaml
