apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  dependsOn:
  - name: infrastructure-crds
  interval: 10m
  retryInterval: 1m
  timeout: 10m
  path: ./infrastructure/controllers
  prune: true
  wait: true
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: argocd
    namespace: argocd
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: sm-operator
    namespace: sm-operator-system
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: cert-manager
    namespace: cert-manager
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: cilium
    namespace: kube-system
  - apiVersion: apps/v1
    kind: Deployment
    name: local-path-provisioner
    namespace: local-path-storage
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: harbor
    namespace: harbor
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: pomerium
    namespace: networking
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: reloader
    namespace: reloader
  - apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    name: seaweedfs
    namespace: storage
  decryption:
    provider: sops
    secretRef:
      name: sops-aws-kms
  sourceRef:
    kind: GitRepository
    name: flux-system
