apiVersion: v1
kind: Secret
metadata:
    name: pomerium-values
    namespace: networking
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:A/bOYH2PmFLqudjtvAYd3URcmmAOLpvzC3GnvT3sGMYGQss0YDA1ELRgC9b6atzf1kxg36M0LZAOWQkucQKnBGvkfQ5ciDE50LBXH4T72QdxOvIwaEA+3x3eL0h7mEcgmI5ZCBjJCaKiVs/F5JclR9VoK8piI84UsXSs+mSJW1W6hDZpIpJez5aqwglA2oqiIGcOKLReAiC0PYXDy8JSwKEoyINrYtknmoTdgK/yTY3/mX6NX576gG991sFNh1k1nzSiUN7gDntr5loCoXxsKHpFP/kCB0wvoNdoLUJR1WDXIlNAoL/538MU4QsqDyGCkgOw2UJIRxo7EXsP/l0pkrhSYp0S,iv:TrinEy540zG8FMCVno5fYvPX1sQN9kIZUCzR1jzt36I=,tag:LkPEhxiGLuZRCaepSxAOZg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    kms:
        - arn: arn:aws:kms:ap-south-1:867344433810:key/835f8130-e33d-4cf8-af3c-4fb5a0bb9d4a
          aws_profile: ""
          created_at: "2026-07-07T11:53:22Z"
          enc: AQICAHh02qo9Ejv0FmnyeqXt197Sx1HR6uYOTtU++egjUu007wHqdnLtKXlCYe81MsUfR6pkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMxVHG5y6jb7NUWx7MAgEQgDuMDrQ+OUvIl/DRV6fh8qJ7tcJahqKaSVZeCWNUlPn1kktL8vJqUY/M9t4kp6RVq7GY52Qkg/uyIANMNg==
    lastmodified: "2026-07-07T11:53:23Z"
    mac: ENC[AES256_GCM,data:Fmi6+9SV3h9ghPw5hdNMahjXt4eNF0KPxmlG0LU49IzkfBzbxyeUzVEVgj5bI/tPUKgdooqhTn3GqZLBLxlva5/BNtGTEl3AaH3mp/WmGvFxYBeY78hssOijJ7yDc/VZilcd5zhfJaKrI2ZYKkIxIqLd/cXHNvCtD3cJaVylHNM=,iv:8nxRiHNKfUjeeQ3C4VLAAAWclhgxunTsDaoWWQOVqCc=,tag:t4vHeicicLgH3Q3YIWv0fA==,type:str]
    version: 3.13.2
