apiVersion: v1
kind: ConfigMap
metadata:
  name: pomerium-routes
  namespace: networking
data:
  values.yaml: |
    config:
      routes:
      - from: https://hubble.otroid.net
        to: http://hubble-ui.kube-system.svc.cluster.local
        policy:
        - allow:
            or:
            - claim/groups: devops
      - from: https://metrics.otroid.net
        to: http://prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        policy:
        - allow:
            or:
            - claim/groups: devops
